FROM considerate/nak-learn:latest

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    libsndfile1 ffmpeg \
    && rm -rf /var/lib/apt/lists/*

# Music processing libraries
RUN pip3 --no-cache-dir install \
    pypianoroll music21 pretty_midi mido pychord librosa essentia soundfile

